language: go

go:
  - tip

matrix:
  fast_finish: true

addons:
  - postgresql: "9.4"

install:
  - export DB_HOST=localhost
  - cd ${HOME}
  - mkdir -p ${HOME}/src/euphoria.io
  - mv ${TRAVIS_BUILD_DIR} ${HOME}/src/euphoria.io/
  - cd ${HOME}/src/euphoria.io/heim

script: ./ci/test.sh

notifications:
  webhooks:
    urls:
      - http://52.10.123.209:8085/travishook
    on_success: always
    on_failure: always
    on_start: never
